-- GroupCart schema.

DROP TABLE IF EXISTS User
DROP TABLE IF EXISTS UserGroup
DROP TABLE IF EXISTS ListItem
DROP TABLE IF EXISTS Favor

CREATE TABLE User (
    ID INTEGER PRIMARY KEY,
    username UNIQUE VARCHAR(32) NOT NULL,
    password VARCHAR(32) NULL,
    firstName VARCHAR(64) NOT NULL,
    lastName VARCHAR(64) NOT NULL,
    groupID INTEGER NULL REFERENCES UserGroup(ID),
);

CREATE TABLE UserGroup (
    ID INTEGER PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
);

CREATE TABLE ListItem (
    ID INTEGER PRIMARY KEY,
    itemName VARCHAR(64) NOT NULL,
    priority INTEGER NOT NULL,
    added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userID INTEGER NOT NULL REFERENCES User(ID),
);

CREATE TABLE Favor (
    ID INTEGER PRIMARY KEY,
    amount REAL NOT NULL,
    reimbursed DATETIME NULL,
    byUserID INTEGER NOT NULL REFERENCES User(ID),
    forUserID INTEGER NOT NULL REFERENCES User(ID),
    itemID UNIQUE INTEGER NOT NULL REFERENCES ListItem(ID),
);

-- Test data.
